### PR TITLE
refactor to create a function to map task id values to text, fix bug when no mapping is provided

### LINKED ISSUE #29: Refactor code for mapping task id values to text to a helper function

### PR DESCRIPTION
**Pull request by elray1**
This would fix #29

### CODE REVIEW

File: src/predevals.js [hunk 1]
```diff
@@ -926,6 +917,25 @@ const App = {
...
+    /**
+     * Map values of a task id variable to human-readable text.
+     * If this.state.task_id_text is undefined or does not contain the task id variable, returns the input values.
+     *
+     * @param taskId string: the task id variable name
+     * @param taskIdValues array[string]: the task id values to map to text
+     */
+    taskIdValuesToText(taskId, taskIdValues) {
+        const thisState = this.state;
+        if (thisState.task_id_text !== undefined && Object.keys(thisState.task_id_text).includes(taskId)) {
```
Comment (elray1) [inline src/predevals.js:932]: the check `thisState.task_id_text !== undefined` is new and fixes a bug that showed up if no task id text mapping was provided.  this screenshot verifies that it works in the dev example (horizontal axis has raw location codes):
image

**Comment by elray1** [comment]
Good question.  I filed a separate issue for it because it feels like a separate slice of work: https://github.com/hubverse-org/predevals/issues/40
